### ISSUE TITLE
Add this template to microsoft learning page

### ISSUE THREAD

**Issue by hemarina** [Azure-Samples/function-eventhub-vnet#3]
https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main
Meta data in readme looks good. You may want to submit onboarding form to add this template to https://learn.microsoft.com/en-us/samples/browse/?expanded=azure&languages=azdeveloper

**Comment by mcollier** [comment]
Onboarding form submitted. Indexing failed on January 29th seemingly due to a couple of invalid product slugs.  Attempting to resolve in #4.

**Comment by mcollier** [comment]
@hemarina This should be in place now - https://learn.microsoft.com/en-us/samples/azure-samples/function-eventhub-vnet/function-eventhub-vnet/
